services:
  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
    environment:
      GF_FEATURE_TOGGLES_ENABLE: externalServiceAccounts
      GF_AUTH_MANAGED_SERVICE_ACCOUNTS_ENABLED: 'true'
