export const testIds = {
  appConfig: {
    container: 'data-testid ac-container',
    openAIAPIKey: 'data-testid ac-openai-api-key',
    openAIBaseUrl: 'data-testid ac-openai-base-url',
    openAIProtocol: 'data-testid ac-openai-protocol',
    defaultModel: 'data-testid ac-default-model',
    thinkingLevel: 'data-testid ac-thinking-level',
    thinkingFormat: 'data-testid ac-thinking-format',
    allowedUsers: 'data-testid ac-allowed-users',
    systemPromptAddendum: 'data-testid ac-system-prompt-addendum',
    allowedPrometheusDatasourceUids: 'data-testid ac-allowed-prometheus-datasource-uids',
    customSkillsEditor: 'data-testid ac-custom-skills-editor',
    customSkillsJson: 'data-testid ac-custom-skills-json',
    customSkillsJsonOpen: 'data-testid ac-custom-skills-json-open',
    customSkillRow: 'data-testid ac-custom-skill-row',
    customSkillAdd: 'data-testid ac-custom-skill-add',
    customSkillEdit: 'data-testid ac-custom-skill-edit',
    customSkillDelete: 'data-testid ac-custom-skill-delete',
    customSkillName: 'data-testid ac-custom-skill-name',
    customSkillDescription: 'data-testid ac-custom-skill-description',
    customSkillContent: 'data-testid ac-custom-skill-content',
    customSkillKeywords: 'data-testid ac-custom-skill-keywords',
    customSkillRegex: 'data-testid ac-custom-skill-regex',
    customSkillToolGroups: 'data-testid ac-custom-skill-tool-groups',
    customSkillResourceAdd: 'data-testid ac-custom-skill-resource-add',
    customSkillResourcePath: 'data-testid ac-custom-skill-resource-path',
    customSkillResourceContent: 'data-testid ac-custom-skill-resource-content',
    submit: 'data-testid ac-submit-form',
  },
  chat: {
    container: 'data-testid oa-chat-container',
    messages: 'data-testid oa-chat-messages',
    composer: 'data-testid oa-chat-composer',
    stop: 'data-testid oa-chat-stop',
    jumpToLatest: 'data-testid oa-chat-jump-to-latest',
    import: 'data-testid oa-chat-import',
    importInput: 'data-testid oa-chat-import-input',
    export: 'data-testid oa-chat-export',
    send: 'data-testid oa-chat-send',
    toolConfirmation: 'data-testid oa-chat-tool-confirmation',
    toolConfirmationApprove: 'data-testid oa-chat-tool-confirmation-approve',
    toolConfirmationDeny: 'data-testid oa-chat-tool-confirmation-deny',
    investigationReport: 'data-testid oa-chat-investigation-report',
  },
};
